void init_ADC(void);
int ADC_channel;
int ADC_threshold;
int	temp_result;
int ADC_result;
//int ADC_value[8];
signed int last_ADC_result;
int final_ADC_result;
volatile char green_sense;
volatile char yellow_sense;
char line_reading;
char counter;
volatile char intersection;
char no_counter;
char no_intersection;
