void forward(char l);
void reverse(char l);
void turn(char l, char r);
void turn_reverse(char l, char r);
void spin_right(char l, char r);
void spin_left(char l, char r);
void breaks(char l);
void point_right(char s);
void point_left(char s);
void point_right_reverse(char s);
void point_left_reverse(char s);
void allign(char s);

void find_theta();
float cos_theta;
float distance_sensor;
float temp_pwm;
void find_theta_single();
char division_factor;
char spin_threshold;
