void init_ADC(void);
int ADC_channel;
int ADC_threshold;
int	temp_result;
volatile char final_temp_result;
volatile int ADC_result;
//int ADC_value[8];
signed int last_ADC_result;
int final_ADC_result;
char counter;
char final_counter;
